package com.cdcrane.social_konnect_backend.users;

import com.cdcrane.social_konnect_backend.roles.Role;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

import java.util.List;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

@DataJpaTest
class UserRepositoryTest {

    @Autowired
    private UserRepository underTest;

    @BeforeEach
    void setUp() {
    }

    @AfterEach
    void tearDown() {
        underTest.deleteAll();
    }

    @Test
    void shouldFindUserByIdWithRoles(){

        // Given
        Role role = new Role();
        role.setAuthority("ROLE_USER");

        ApplicationUser user1 = ApplicationUser.builder()
                .username("user1")
                .password("password1")
                .email("user1@test.com")
                .roles(List.of(role))
                .build();

        ApplicationUser saved = underTest.save(user1);

        // When
        ApplicationUser result = underTest.findByIdWithRoles(saved.getId());

        // Then
        assertThat(result.getUsername()).isEqualTo("user1");

        assertThat(result.getRoles()).isNotNull();
    }

    @Test
    void shouldNotFindUserByIdWithRoles(){

        // Given no users with the correct id

        // When
        ApplicationUser result = underTest.findByIdWithRoles(999);

        // Then
        assertThat(result).isNull();
    }

    @Test
    void shouldFindAllUsersWithRoles(){

        // Given
        Role role1 = new Role();
        role1.setAuthority("ROLE_USER");

        Role role2 = new Role();
        role1.setAuthority("ROLE_ADMIN");

        ApplicationUser user1 = ApplicationUser.builder()
                .username("user1")
                .password("password1")
                .roles(List.of(role1))
                .build();

        ApplicationUser user2 = ApplicationUser.builder()
                .username("user2")
                .password("password2")
                .roles(List.of(role2))
                .build();

        underTest.save(user1);
        underTest.save(user2);

        // When
        List<ApplicationUser> results =  underTest.findAllWithRoles();

        // Then
        assertThat(results).isNotNull();

        assertThat(results.size()).isEqualTo(2);

        assertThat(results.get(0).getRoles()).isNotNull();
        assertThat(results.get(1).getRoles()).isNotNull();
    }

    @Test
    void shouldNotFindAllUsersWithRoles(){

        // Given no users

        // When
        List<ApplicationUser> results =  underTest.findAllWithRoles();

        // Then
        assertThat(results.isEmpty()).isTrue();


    }

    // No point testing other query methods as they are generated by Spring Data JPA and are already tested.
}